### ISSUE TITLE
Did you use your own machine for Yelp Food Reviews' Analysis?

### ISSUE THREAD

**Issue by aliarsalankazmi** [skipgram/modern-nlp-in-python#3]
Hi Patrick,

Apologies, I tried finding other means of approaching you and asking this question but could not find any.

Did you conduct all of the analyses in the Yelp Food Reviews on your machine, without resorting to AWS or others? Because I need to do some analyses myself on 20GiB text data, and I want to try Python, if you used it without encountering RAM issues.

Thanks ever so much in advance.

**Comment by pwharrison** [comment]
No worries! My contact information is in the notebook, for future reference.

Yes, I ran all of the analyses in _Modern NLP in Python_ on a personal machine. For all the parts that would become memory-intensive, I use generator functions to read the data from disk incrementally, rather than trying to hold all of the data in memory at once.
